version: '3.4'

services:
  secchecklist:
    image: secchecklist
    build:
      context: .
      dockerfile: ./Dockerfile
    command: 
    - api
    - serve
    - --http 
    - 0.0.0.0:80
    environment:
      - CHECKLISTS_DSN=test:test@tcp(db)/test
      - IFACTS_BASEURL=${IFACTS_BASEURL}
      - IFACTS_CLIENT_ID=${IFACTS_CLIENT_ID}
      - IFACTS_CLIENT_SECRET=${IFACTS_CLIENT_SECRET}
    ports:
      - 8080:80
    volumes:
    - ./data:/data

  client:
    image: secchecklist
    build:
      context: .
      dockerfile: ./Dockerfile
    command: 
    - client
    - --http 
    - 0.0.0.0:80
    - --api
    - http://localhost:8080
    environment:
      - CHECKLISTS_DSN=test:test@tcp(db)/test
    ports:
      - 8081:80
    volumes:
    - ./data:/data

  init-db:
    image: secchecklist
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - CHECKLISTS_DSN=test:test@tcp(db)/test
      - EXCEL_PATH=${EXCEL_PATH}
      - SHEET_NAME=${SHEET_NAME}
    command:
    - api
    - load
    - --from 
    - ${EXCEL_PATH}
    - --fromSheet 
    - ${SHEET_NAME} 
    volumes:
      - ./data:/data
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_USER: test
      MARIADB_DATABASE: test
      MARIADB_PASSWORD: test
    volumes:
      - ./database/startup:/docker-entrypoint-initdb.d
      - checklists:/var/lib/mysql
    ports:
    - "3306:3306"

  db-admin:
    image: adminer
    ports:
      - 8090:8080
    depends_on:
    - db

volumes:
  checklists: