version: '3.4'

services:
  secchecklist:
    image: secchecklist
    build:
      context: .
      dockerfile: ./Dockerfile
    command: 
    - -from 
    - ${EXCEL_FILEPATH}
    - -fromSheet 
    - ${SHEET_NAME} 
    - -db 
    - -init 
    - -http 
    - 0.0.0.0:80
    environment:
      - CHECKLISTS_DSN=test:test@tcp(db)/test
    ports:
      - 8080:80
    volumes:
    - ./data:/data

  db:
    image: mariadb
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_USER: test
      MARIADB_DATABASE: test
      MARIADB_PASSWORD: test
    volumes:
      - ./database/startup:/docker-entrypoint-initdb.d
      - checklists:/var/lib/mysql
    ports:
    - "3306:3306"

  db-admin:
    image: adminer
    ports:
      - 8090:8080
    depends_on:
    - db

volumes:
  checklists: