#!/usr/bin/env bash
set -e

GOOS=$(go env GOOS)
GOARCH=$(go env GOARCH)

BASE_BIN=dist/secctrls
if [ "${GOOS}" == "windows" ]; then
    BASE_BIN=${BASE_BIN}.exe
fi

rm -f ${BASE_BIN}

FLAGS=()
if [ -n "${VERBOSE}" ]; then
    FLAGS+=(-v)
fi

echo "Building ${BASE_BIN} for ${GOOS}/${GOARCH}"

GO_BUILD_CMD="go build -ldflags"
GO_BUILD_ARGS="-s -w"

CGO_ENABLED=0 ${GO_BUILD_CMD} "${GO_BUILD_ARGS}" ${FLAGS} -o "${BASE_BIN}" ./main.go
