#!/usr/bin/env bash
set -e

BASE_BIN=dist/secctrls
rm -f ${BASE_BIN}

FLAGS=()
if [ -n "${VERBOSE}" ]; then
    FLAGS+=(-v)
fi

echo "Building ${BASE_BIN}"

GO_BUILD_CMD="go build -ldflags"
GO_BUILD_ARGS="-s -w"

OS_PLATFORM_ARG=(linux windows darwin)
OS_ARCH_ARG=(amd64)

for OS in "${OS_PLATFORM_ARG[@]}"; do
    BIN_EXT=''
    if [ "${OS}" == "windows" ]; then
        BIN_EXT='.exe'
    fi
    for ARCH in "${OS_ARCH_ARG[@]}"; do
        echo "Build binary for ${OS}/${ARCH}..."
        GOARCH=${ARCH} GOOS=${OS} CGO_ENABLED=0 ${GO_BUILD_CMD} "${GO_BUILD_ARGS}" ${FLAGS} -o "${BASE_BIN}_${OS}-${ARCH}${BIN_EXT}" ./main.go
    done
done

OS_PLATFORM_ARG=(linux darwin)
OS_ARCH_ARG=(arm64)

for OS in "${OS_PLATFORM_ARG[@]}"; do
    for ARCH in "${OS_ARCH_ARG[@]}"; do
        echo "Build binary for ${OS}/${ARCH}..."
        GOARCH=${ARCH} GOOS=${OS} CGO_ENABLED=0 ${GO_BUILD_CMD} "${GO_BUILD_ARGS}" ${FLAGS} -o "${BASE_BIN}_${OS}-${ARCH}" ./main.go
    done
done

